import { Bucket } from '../classes/bucket';
import { Stream } from '../classes/stream';

export const TEST_BUCKETS_GROSS: Bucket[] = [
  {
    id:"1",
    label:"403b Retirement",
    type:"gross",
    method:"save",
    contribution:7,
    investmentMin:0,
    investmentReturnLower:6,
    investmentReturnUpper:8,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:13500,
    annualContributionTotal: 0,
    expenseType:null,
    debtBalance:null,
    debtInterestRate:null,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  },
  {
    id:"2",
    label:"Defined Benefit Plan",
    type:"gross",
    method:"save",
    contribution:9,
    investmentMin:0,
    investmentReturnLower:0,
    investmentReturnUpper:0,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:0,
    annualContributionTotal: 0,
    expenseType:null,
    debtBalance:null,
    debtInterestRate:null,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  },
  {
    id:"3",
    label:"Benefits",
    type:"gross",
    method:"spend",
    contribution:5,
    investmentMin:null,
    investmentReturnLower:null,
    investmentReturnUpper:null,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:null,
    annualContributionTotal: 0,
    expenseType:"recurring",
    debtBalance:0,
    debtInterestRate:0,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  }
];

export const TEST_BUCKETS_TAX: Bucket[] = [
  {
    id:"4",
    label:"Income Taxes",
    type:"taxes",
    method:null,
    contribution:10,
    investmentMin:null,
    investmentReturnLower:null,
    investmentReturnUpper:null,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:null,
    annualContributionTotal: 0,
    expenseType:null,
    debtBalance:null,
    debtInterestRate:null,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  }
];

export const TEST_BUCKETS_NET: Bucket[] = [
  {
    id:"5",
    label:"Monthly Expenses",
    type:"net",
    method:"spend",
    contribution:50,
    investmentMin:null,
    investmentReturnLower:null,
    investmentReturnUpper:null,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:null,
    annualContributionTotal: 0,
    expenseType:"recurring",
    debtBalance:0,
    debtInterestRate:0,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  },
  {
    id:"6",
    label:"Credit Card",
    type:"net",
    method:"spend",
    contribution:10,
    investmentMin:null,
    investmentReturnLower:null,
    investmentReturnUpper:null,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:null,
    annualContributionTotal: 0,
    expenseType:"debt",
    debtBalance:12000,
    debtInterestRate:15,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  },
  {
    id:"7",
    label:"Savings",
    type:"net",
    method:"save",
    contribution:30,
    investmentMin:0,
    investmentReturnLower:1,
    investmentReturnUpper:1,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:0,
    annualContributionTotal: 0,
    expenseType:null,
    debtBalance:null,
    debtInterestRate:null,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  },
  {
    id:"8",
    label:"Roth IRA",
    type:"net",
    method:"save",
    contribution:10,
    investmentMin:3000,
    investmentReturnLower:7,
    investmentReturnUpper:8,
    monthInvestmentReturn: 0,
    investmentReturnPercentage:0,
    annualContributionLimit:5500,
    annualContributionTotal: 0,
    expenseType:null,
    debtBalance:null,
    debtInterestRate:null,
    returnsTotal:0,
    monthTotal:0,
    annualTotal:0,
    total:0
  }
];

export const TEST_STREAMS: Stream[] = [
  {
    label: "Main Income",
    lowerLimit: 5000,
    upperLimit: 6500,
    monthTotal: 0,
    annualTotal: 0,
    total: 0
  }
];